import { AuthBanner } from "components/AuthBanner";
import SigninForm from "components/form/signin-form";
import SignupForm from "components/form/signup";
import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import { useRouter } from "next/router";
import Logo from "public/icons/pp_icon.svg";
import { useEffect, useState } from "react";

export default function Auth() {
    const { query } = useRouter();
    const [isLoginPage, setIsLoginPage] = useState<boolean>(true);
    const [error, setError] = useState<boolean>(false);

    useEffect(() => { // query param da redirect = x gelirses
        if (query?.redirect) {
            switch (query.redirect) {
                case "signin":
                    return setIsLoginPage(true);
                case "signup":
                    return setIsLoginPage(false);
                case "error":
                    return setError(true);
            }
        }
    }, [query]);

    return (
        <>
            <Head>
                <title>PicPath | Welcome</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/pp_icon.svg" />
            </Head>
            <main className="flex h-screen w-full justify-center items-center">
                {isLoginPage ? (
                    <>
                        <AuthBanner isLogin={isLoginPage} setIsLogin={setIsLoginPage} />
                        <div className="w-1/2 flex items-center justify-center m-auto">
                            <SigninForm error={error} setError={setError} />
                        </div>
                    </>
                ) : (
                    <>
                        <div className="w-1/2 flex items-center justify-center m-auto">
                            <SignupForm error={error} setError={setError} />
                        </div>
                        <AuthBanner isLogin={isLoginPage} setIsLogin={setIsLoginPage} />
                    </>
                )}
                <Link href="/">
                    <Image
                        src={Logo}
                        alt="PicPath"
                        width={40}
                        height={40}
                        className="absolute top-5 left-7"
                    />
                </Link>
            </main>
        </>
    );
}