import { Button } from "@material-tailwind/react";
import Layout from "layout";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>PicPath | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pp_icon.svg" />
      </Head>
      <Layout>
        <main>
          <h1 className="text-5xl text-center mt-5 text-green-800 font-bold">Hello {data?.user.username}!</h1>
          <section className="w-1/2 m-auto flex justify-around items-center mt-10">
            <Button onClick={() => signOut()} variant="outlined">Sign out</Button>
          </section>
        </main>
      </Layout>
    </>
  );
}