import Head from "next/head";
import Image from 'next/image';
import Icon1 from "../public/pp_icon.svg";
import Icon2 from "../public/pp_icon_alternative.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>PicPath | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pp_icon.svg" />
      </Head>
      <main>
        <h1 className="text-5xl text-center mt-5 text-green-800 font-bold">Hello Pic Path!</h1>
        <section className="w-1/2 m-auto flex justify-around items-center mt-10">
          <Image
            src={Icon1}
            alt="PicPath"
          // width={500} automatically provided
          // height={500} automatically provided
          // blurDataURL="data:..." automatically provided
          // placeholder="blur" // Optional blur-up while loading
          />
          <Image
            src={Icon2}
            alt="PicPath"
          // width={500} automatically provided
          // height={500} automatically provided
          // blurDataURL="data:..." automatically provided
          // placeholder="blur" // Optional blur-up while loading
          />
        </section>
      </main>
    </>
  );
}
